name: 'aws-sam-cli-test'
description: 'Run unit test of an AWS SAM based project'
inputs:
    who-to-greet:
        description: 'Who to greet'
        require: true
        default: 'world'
outputs:
    time:
        description: 'The time we greeted you'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.who-to-greet }}
branding:
    icone: "tool"
    color: "grey-dark"